### ISSUE TITLE
DNS query failure in async paradigm 

### ISSUE THREAD

**Issue by novi** [orlandos-nl/NioDNS#4]
DNS request will failure with [this async test](https://github.com/novi/NioDNS/commit/08dd4a5002064f2cbd80901338ccacc656453452) as expected.

```
2019-09-17 15:14:22.499290+0900 xctest[7603:427732] [si_destination_compare] send failed: Invalid argument
2019-09-17 15:14:22.499516+0900 xctest[7603:427732] [si_destination_compare] send failed: Undefined error: 0
NioDNS/Tests/DNSClientTests/DNSClientTests.swift:54: error: -[DNSClientTests.DNSClientTests testSRVRecordsAsync] : Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "getSRVRecords".
```

No callback is called and it shows `send failed` error in console.

**Comment by Joannis** [comment]
I'm sorry that I missed this issue. Is this still an issue with the recent versions, since I am relying on this code.

**Comment by Joannis** [comment]
Closing this, as `send failed` is a known bug in SwiftNIO and doesn't affect NIODNS

**Comment by alessionossa** [comment]
I think the `send failed` error is unrelated to the issue reported by @novi , and that you can reproduce with his test.
The `send failed` issue is just a "false error", but the request is correctly sent to the server.
The error here, instead, is that for some reason the library doesn’t complete/return the Future when using asynchronous code instead of `.wait()`.

I have faced the same issue and found this thread after I checked with Wireshark that the request was correctly sent to the server and the server responded correctly.

**Comment by Joannis** [comment]
@alessionossa might it be that Swift deallocated/deinit-ed the DNS client while waiting for a response?

**Comment by alessionossa** [comment]
I just read again [Notes](https://github.com/orlandos-nl/NioDNS#notes) and this is probably the case. Thank you for the fast response!

I will open another issue related to `ProtocolError` as soon as I will reproduce the issue without sensitive data.

**Comment by alessionossa** [comment]
I think this issue can now be closed

**Comment by Joannis** [comment]
Thanks! Will do.
